tozny/e3db-clients-go

README.md
authClient/api.go
authClient/authClient.go
authClient/authClient_test.go
main_test.go
pdsClient/pdsClient.go
pdsClient/pdsClient_test.go

- Add client code and integration test for calling auth service validate endpoint.
- Standardize capitalization of client naming.
Companion PR:
- https://github.com/tozny/e3db-auth/pull/26

WASH-454-auth-token-validation-service

---

main.go
pdsClient/pdsClient.go
pdsClient/pdsClient_test.go

This is to add a new method that proxies user calls to PDS for the Executer it takes a bearer token and manually constructs the authorization header for the request.
Companion PR to WASH-501 on e3dbsearchservice, waiting on merge of WASH-500 to make PR for that.

Add New Client To Proxy User Request

---

pdsClient/api.go

List Record Call doesn't parse file meta information because it doesn't have the associated type; added in to support returning large file information in sdks.

Add Parsing of FileMeta Information

---

pdsClient/api.go
pdsClient/pdsClient.go
pdsClient/pdsClient_test.go

- Add InternalAllowedReads method to pds client, tests. 
- Update Record struct to work with all PDS endpoints.

Add InternalAllowedReads method to pds client

---

pdsClient/api.go
pdsClient/pdsClient.go
pdsClient/pdsClient_test.go

Work in progress.
Depends on https://github.com/tozny/pds-service/pull/138 to function, and will be tested once that is merged into PDS.
More tests for value:
- if the endpoint allows removing one time range (all records modified after this time)
- test actual modified record, not just creation, is returned by endpoint

[WIP] Call internal modified records endpoint

---

README.md
authClient/authClient.go
main.go

- Create auth http client once and re-use across calls to allow for maximal re-use of Tozny JWT Token.

Reuse e3db auth token as long as it is valid

---

accountClient/accountClient.go
accountClient/accountClient_test.go
accountClient/api.go

- Add method for new account service get stripe id internal endpoint
- Adds tests for those methods
- Refactors test file to not have duplicate code
- [Companion PR](https://github.com/tozny/account-service/pull/58)

Add methods for account internal get stripe id

---

accountClient/accountClient.go
accountClient/api.go
clientServiceClient/api.go
clientServiceClient/clientServiceClient.go
main.go

Adds registration and creation of registration tokens to the accountClient. However account service comes with its own Auth token, and it serves up extra data information in the headers of the response which we abstract out with e3db-clients-go leading to near duplicate functions. Suggestions on how to handle this welcome, focus was more on getting client-service working than making this client super clean so there might be a really simple way I've overlooked
companion PR https://github.com/tozny/client-service/pull/7

Account Registration Endpoints

---

accountClient/accountClient.go
accountClient/api.go

Bug introduced in https://github.com/tozny/e3db-clients-go/pull/34 forgot to rename an additional type after a refactor. Auto-merging because it's a small semantic, but breaking, change.

Bugfix for renamed field

---

clientServiceClient/api.go
clientServiceClient/clientServiceClient.go

Adds client calls for the internal batchpublic endpoint to get a client's public information
Companion PR: https://github.com/tozny/client-service/pull/11

Initial batch public endpoints

---

.env
README.md
accountClient/accountClient.go
accountClient/accountClient_test.go
authClient/authClient.go
authClient/authClient_test.go
main_test.go
pdsClient/pdsClient.go
pdsClient/pdsClient_test.go
searchIndexerClient/indexerClient_test.go
test/test.go

This PR was initially meant to pull out and consolidate shared testing helper code from other repos, but I found that the testing methods within this repo also use the bad register endpoint. 
This PR:
- Removes bad testing methods
- Removes non-existent endpoints
- Consolidates shared test helper methods

E3db-Clients: Client Service Testing Cleanup 

---

accountClient/accountClient.go

- Endpoint no longer exists
- Was deprecated following introduction of billing service

Remove get internal acount info method

---

clientServiceClient/api.go
clientServiceClient/clientServiceClient.go
crypto.go
main.go
pdsClient/pdsClient.go
storageClient/api.go
storageClient/storageClient.go
storageClient/storageClient_test.go
storageClient/storageTest.go

Defines some shared types used across services like the additional tozny client contextual information and public encryption keys.
Ports over crypto methods from our SDK so we can use proper encryption in Integration tests
Adds storage client to for use in integration tests against storagev2/notes service.

Add type safety to keys and crypto methods to support tozstore-like operations

---

storageClient/storageClient.go

Adds call to storage/notes client for a PUT request on /notes. This endpoint allows you to upsert a note based on IDString conflicts. It will be used to change a identity client's password.

Upsert note call for storage client

---

identityClient/api.go
identityClient/identityClient.go
identityClient/identityClient_test.go

- Tests.
- Update Realm and RegisterIdentity API responses to include the tozny client id of the realm backup identity if set.

Add identity client methods for setting the realm backup identity. 

---

identityClient/api.go
identityClient/identityClient.go
storageClient/api.go
storageClient/storageClient.go
storageClient/storageClient_test.go

- Update storageClient API definitions for activate challenge endpoint to include more fully specified activated challenges.
- Fix identity api struct semantic error.

Add storageClient API definitions for TozID EACP 

---

authClient/authClient.go

ValidateToken did not handle error received before attempting to
dereference the response.

Handle nil ptr on authentication

---

identityClient/api.go
identityClient/identityClient.go
identityClient/identityClient_test.go

Adds methods for interacting with the new LDAP cache endpoint in identity service.

Add internal ldap cache endpoints to identity client

---

.env
accountClient/accountClient.go
accountClient/accountClientV2.go
accountClient/accountClient_test.go
accountClient/api.go

Eli & I decided to add HostV2 to the E3dbAccoundClient so that these tests can be done, but I would like feedback on how other people think this should be done.
We're thinking there are three options:
1. 1 client with hosts for v1 and v2
2. 2 different clients with 1 host each
3. 1 client with 1 host where checks are managed by Cyclops

Added accountClient v2 health and service checks

---

Makefile
identityClient/api.go
identityClient/identityClient_test.go
storageClient/storageClient_test.go

During deployment we found tests for identity that required a bit of fixing to pass with our new application roles! Added new makefile rules and deleted a miscellaneous log line in storage

fixing tests for new default application roles

---

README.md
authClient/api.go
crypto.go
go.mod
go.sum
identityClient/api.go
identityClient/identityClient.go
identityClient/identityClient_test.go
pdsClient/pdsClient.go
secretstream/secretstream_new.go
storageClient/storageClient.go
storageClient/storageClient_test.go

- Adds identity flow methods
- Adds storage service methods for fetching notes by name
- Adds crypto methods for note reading and validation
- This does not currently have tests as the functionality to derive credential notes is in e3db-go (which will cause a circular dependency) we may want to shift that code here to allow for better testing

Add identity and storage methods to support sdk-login

---

crypto.go
storageClient/storageClient.go

these key length constants are used to check that the key lengths in a client credential object are valid.

Secret key sizes

---

Makefile
identityClient/identityClient_test.go

Improve identityClient_test stability
When running against the development environment tests can randomly fail
- re-order identity test methods, move all helpers to the top of the file
- this makes it easier to comment out large amount of tests if needed
- increase test suite timeout (20 minutes instead of default 10 minutes)
- avoid `panic: test timed out after 10m0s` errors when running against development
- refactor uniqueString helper to use random int instead of timestamp
- ensure we use this helper for all realm names
- add retry for realm creation
- currently retries once after failure
- so far in all my test runs a single retry appears to be enough

[WR-release] identityClient_test stability improvements

---

keycloakClient/api.go
keycloakClient/keycloakClient.go

I was digging deeply into a race condition that was causing identitiy management tests to fail, which is the same race condition that causes us to need retry logic on the identity tests in this repo.
Changes to this repo:
* i made the mutex wrap the entire `GetTokenInfo` func. 
* in the best case where it finds the token in the `tokens` map, it makes three extra boolean checks before releasing the lock. in the worst case, it refreshes & replaces the token. The lock should still be held as a race condition exists in which it locks for read, some other goroutine grabs the token, this code replaces the token (invalidating the old), and then the other goroutine is attempting to use a no longer valid one.
* as will be seen in my identity management PR, if you grab the token as a string, there …

[PLAT-731] token races

---

.env
identityClient/identityClient_internal_test.go

- Adds a test that writes more audits than the threshold for an
Identity's account, and confirms that the account becomes locked
Draft PR for now. Still want to do some cleanup.

[WASH-1045] Test locking an Identity's account

---

Makefile
go.sum
pdsClient/pdsClient_test.go

Once the new version of `e3db-clients-go` was added to `e3dbSearchService` existing tests started to fail. The failures were coming from helper methods in pds client test so it made sense to debug those here:
The fix was to use Cyclops Host instead of Client Host  when calling `test.CreatePDSClient` resolving:
- `server http error 404`  when registering a client
- request was going to accounts on port 8003, but accounts runs on port 8002
Cyclops can route the request to the proper service
Also:
- add make task for running pds tests
- change all `t.Errorf` to `t.Fatalf` so test execution stops after the first error

[WASH-1020] fix pdsClient tests

---

storageClient/storageClient_test.go

These are tests from storage service that do not hit internal endpoints. They have been ran against dev and both pass.

[WASH-1049] Add login note and pass reset tests

---

hookClient/api.go

go to build a service that hasn't been changed in over a year, and got this
```
Step 7/17 : RUN go mod download
---> Running in 94e8a2c061b5
go mod download: github.com/tozny/e3db-clients-go@v0.0.101-0.20200925182558-d06f88c0fca6: invalid version: unknown revision d06f88c0fca6
```
unpublished commit
https://github.com/tozny/e3db-clients-go/commit/d06f88c0fca6
update matches what the service api is expecting
https://github.com/tozny/hook-service/blob/master/api/api.go#L27
And integration test for the code path continue to pass 
https://github.com/tozny/hook-service/blob/master/hook_test.go#L344

publish previous commits which while unmerged have been deployed to production since Oct 21.

---

identityClient/identityClient_test.go

Using bootstrap client against any env besides local will not work
Use `UpsertAccessPolicies` instead of `InternalUpsertAccessPolicies` for MPC test setup

[PAM] do not use internal methods for test setup

---

identityClient/api.go
identityClient/identityClient.go

Making an API Spec Change but thought it would be easier to show this first:
Current Flow:
Primary Initiates Connection (Queen Auth)
Shadow Configures to hook up to that connection ( Queen Auth) 
* During the hook up, the shadow calls the primary to activate the connection (api credential auth)  <-- **that is this endpoint** 
Currently it just returned success or error now it will return ldap config! 
Next PR will be API Spec

[WR263] LDAP Hook Up upon successful connection

---

identityClient/identityClient.go
keycloakClient/keycloakClient.go

Fixes a bug in which a reference to the response object was not being passed into `MakeSignedServiceCall` for `ListIdentitiesMFACredentials` and `RegisterMFADevice`. 
Adds a new Keycloak Client method to call Keycloak's `/credentials` endpoint, which returns a list populated with each credential the user has.

[WR-388] Add GetUserCredentials keycloak method

---

identityClient/api.go

though we haven't made use of them, the login context can be more than
just strings. it is especially helpful to be anything so that it can
be a list of items.
**this is a breaking change**, as previously used login context values must
now be cast to strings.
i'm open for debate on whether or not this change should happen in this way. my main justification is that we state this repo is for internal use and this makes all login flow funcs more powerful.
it is used by one handler in identity service & the login method of e3db-go. if we implemented this change by introducing another client method with the new return type, both these login flow uses would need updated to the new thing.
my primary motivation for this is that the webauthn login flow should support multiple authentication …

[WR-387] change login context from string -> interface{}

---

keycloakClient/api.go
keycloakClient/keycloakClient.go

listing the auth providers allows us to check if an auth provider exists
before attempting to add it to an auth flow execution.

[WR-414] add method for listing auth providers

---

keycloakClient/keycloakClient.go

Keycloak's remove roles from user API expects array of role ids under DELETE http method but our existing delete wrapper is not sending any body with the DELETE API call. So i have added new method to send body with DELETE API call.
If we do not pass any data in DELETE API call then Keycloak removes all the roles from the user. So far this has been called in   "SyncIdentityMembershipAndRoles" handler method.
Ref: DELETE /{realm}/users/{id}/role-mappings/realm

Plat 1409 add data to delete api

---

storageClient/api.go
storageClient/storageClient.go

A new API wrapper which calls Storage Service 2 to remove user from tozstore group when their access is expired.

New API wrapper for internal delete group members.

---

crypto.go
storageClient/storageClient.go

- Email update requires update in storage service's email_eacp table. So new storage service internal API wrapper is added. This is used to call SS from Identity Service.

Update eacp email.

---

clientServiceClient/api.go
clientServiceClient/clientServiceClient.go

Two API endpoints:
1. Get all clients with IsDeleted status.
2. Reset cleanup table row so that client delete routine will clean un-shared floating records.

Tozflow 691 internal clientinfo

---

identityClient/api.go

Edit Mode filed in User Federation Provider creation(Ex:LDAP) became mandatory in KC19 so this has been added to our terraform provider.
https://github.com/tozny/terraform-provider-tozny/tree/WR-595-Keycloak-Upgrade

Edit mode added to provider connection settings.

---

clientServiceClient/api.go
clientServiceClient/clientServiceClient.go
storageClient/api.go

Added new attribute to pass delete_shared_records as option to delete endpoint. Adjusted API method from DELETE to POST and modified URL as well.

User delete enhancement. Client cleanup API changes.

---

clientServiceClient/clientServiceClient.go

Description:
I had merged user delete enhancement API changes which should not be until all the dependent services got tested. So i have to revert it because it impacts IDMS.
This is a revert of this PR https://github.com/tozny/e3db-clients-go/pull/376
Test:
When a user is deleted from Flow Identities all of their shared records will not be deleted. This change actually introduced a new option to force delete all shared records but it is put on hold.

Revert user delete enhancement changes

---

keycloakClient/keycloakClient.go
main.go

Updated "ReturnRawServiceCall" method to return Keycloak error. Previously, when a downstream service return error, the response body was ignored(not read). 
Instead, it returns a error string with request URL and status text. 
Now, i have made a change to read response body and if it is not null then it will return the error response else fall back to the legacy error message.

Return error message from downstream service.
