tozny/e3db-clients-go

README.md
pdsClient/pdsClient.go
searchIndexerClient/api.go
searchIndexerClient/indexerClient.go
searchIndexerClient/indexerClient_test.go

Add go client for talking to search service indexer.

---

searchIndexerClient/api.go
searchIndexerClient/indexerClient.go
searchIndexerClient/indexerClient_test.go

companion pr to https://github.com/tozny/e3dbSearchService/pull/43
updates indexer client to support batch index call with appropriate types

Batch index call

---

go.mod
go.sum
pdsClient/api.go
pdsClient/pdsClient.go
pdsClient/pdsClient_test.go

Add pdsClient method for authorizing a client to share records with other clients, integration tests.

Add pdsClient method for adding authorizer

---

Makefile
README.md
hookClient/api.go
hookClient/hookClient.go
hookClient/hookClient_test.go

- Add hook client with support for creating/listing/deleting hooks. 
- Integration tests.
- Doc updates

Add hook client with support for creating/listing/deleting hooks. 

---

go.mod
go.sum
pdsClient/api.go
pdsClient/pdsClient.go
pdsClient/pdsClient_test.go

- Add methods for batch get and proxy batch get of a users records. 
- Integration tests.
- Companion [PR](https://github.com/tozny/pds-service/pull/142)

BatchGetRecords

---

pdsClient/api.go
pdsClient/pdsClient.go
pdsClient/pdsClient_test.go

- Companion [PR](https://github.com/tozny/pds-service/pull/146)
- Promote InternalModifiedRecords to more fleshed out internal search method.

Add method and integration test for internal allowed_reads search endpoint.

---

README.md
accountClient/accountClient_test.go
authClient/authClient.go
authClient/authClient_test.go
go.mod
go.sum
hookClient/hookClient_test.go
main.go
main_test.go
pdsClient/pdsClient_test.go
searchIndexerClient/indexerClient.go
searchIndexerClient/indexerClient_test.go

Companion [utils-go PR](https://github.com/tozny/utils-go/pull/19)

Update clients to accept and use per service routing config.

---

metricClient/api.go

Accompanying tag change here https://github.com/tozny/metrics-service/pull/15

change json include logs to exclude logs

---

metricClient/metricClient.go

namespace change to match this PR https://github.com/tozny/api-specs/pull/83

namespace change to append /requests for current Metrics endpoints

---

accountClient/accountClient.go

Adds methods to AccountClient to call service and healthcheck endpoints

AccountClient servicecheck and healthcheck

---

.gitignore
accountClient/accountClient.go
accountClient/accountClient_test.go
accountClient/api.go
test/test.go

Adds the internal endpoint request to the client and tests it

Add client info signature validation

---

clientServiceClient/api.go
clientServiceClient/clientServiceClient.go

Adds new client for the client-service, to call the four new endpoints
companion PR https://github.com/tozny/client-service/pull/7

Client-service client

---

clientServiceClient/api.go
clientServiceClient/clientServiceClient.go
main.go

Companion PR here: https://github.com/tozny/client-service/pull/9. Adds client functions to call new endpoints

client service public endpoint

---

clientServiceClient/api.go
clientServiceClient/clientServiceClient.go

Adds admin call to enable/disable clients for this PR https://github.com/tozny/client-service/pull/12

Enable/disable client calls for client-service

---

clientServiceClient/api.go
clientServiceClient/clientServiceClient.go

Update Client service client to have internal patch endpoint: 
companion PR: https://github.com/tozny/client-service/pull/10

initial internal patch implemenation

---

clientServiceClient/api.go
clientServiceClient/clientServiceClient.go
clientServiceClient/clientServiceClientTest.go

update client-service calls in accordance with this PR https://github.com/tozny/client-service/pull/14

Client service account id for client id and admin list params

---

clientServiceClient/api.go
clientServiceClient/clientServiceClient.go

Adds calls to the two new GET endpoints in client-service here: https://github.com/tozny/client-service/pull/17

Client service authN context calls

---

billingClient/api.go
billingClient/billingClient.go

Tests will get added in a later implementation, this sprint

Initial billing service implementation

---

billingClient/api.go
billingClient/billingClient.go

Client is tested for all methods in billing service

Additional billing endpoints

---

billingClient/billingClient.go

Companion [PR](https://github.com/tozny/billing-service/pull/11)

Standardize Billing url construction.

---

accountClient/accountClient.go
accountClient/api.go

Adds client call to hit the internal endpoint /info for account service/metrics service

Account client Info endpoint

---

accountClient/accountClient.go
accountClient/api.go

- This is a breaking change for client service if picked up before new account service is deployed

Update Account Service Registration token requests

---

accountClient/api.go
go.sum

Necessary for populating contact information in notification-service

Add Name field to InternalAccountInfoResponse

---

storageClient/api.go
storageClient/storageClient.go

Adds Note Challenge Endpoint

---

LICENSE.md
crypto.go
hookClient/hookClient_test.go
pdsClient/api.go
pdsClient/pdsClient.go
pdsClient/pdsClient_test.go
test/test.go

- Fully implement encryption and decryption of records.
- Fully implement sharing and authorizer flows.

Updates for using e3db-clients-go in wind river demo

---

test/test.go

Very useful for testing notifications requiring manual verification

Adds a method to create an account with a specific email

---

storageClient/api.go
storageClient/storageClient.go

- Minor Struct update following testing

Add params to read note to support eacp

---

billingClient/api.go

Update billing service client

---

main.go

Ironically, takes out internal boolean value in favor of a list of AuthorizedClientIDs.
Previously, this authenticator would just ignore the internal boolean and check if the authn header was present. This lead to a bug in notification service where the route was publicly available, but not actually guarded by the bootstrap client.
This is a breaking change for users of this method: however updates to the notification and identity will follow. This authenticator should not be allowed to fail open, however adding a nil client id 0000-...-0000 will let fail open pass. **_If you know of other services that use this method that slipped my search please let me know_**

Fix xToznyAuthnAuthenticator to obey (some) internal boolean

---

pdsClient/api.go
storageClient/api.go
storageClient/storageClient.go

- Add Records post
- Add Files post
- Add Files patch

Add Write Record and File to storage-service client

---

clientServiceClient/api.go
clientServiceClient/clientServiceClient.go

Failed to change base branch before merging this is an approved duplicate of https://github.com/tozny/e3db-clients-go/pull/99

[DUP] Add client to call client service email verification #99

---

crypto.go
identityClient/api.go
identityClient/identityClient.go
tsv1.go

- Fixes singing key generation bug as well

Makes realm names in keycloak paths lowercase

---

Makefile
accountClient/accountClient.go
accountClient/accountClient_test.go
accountClient/api.go

- Add delete registration token methods
- Implement list registration tokens method. 
- Tests.

Add method for managing registration tokens

---

Makefile
crypto.go
identityClient/api.go
identityClient/identityClient.go
identityClient/identityClient_test.go
main.go
pdsClient/pdsClient.go
pdsClient/pdsClient_test.go
storageClient/storageClient.go

Implement client method for fetching tozny hosted broker info. 

---

pdsClient/pdsClient.go
pdsClient/pdsClient_test.go

Implement deauthorize method. 

---

identityClient/api.go
identityClient/identityClient.go
identityClient/identityClient_test.go

- Merge less generic application role in with generic Role type

Add client methods and tests for realm group role mappings RUD.

---

storageClient/api.go
storageClient/storageClient.go

Added Function for Read Group Endpoint, Plus a change from previous PR that didn't get fixed.

Changes for Read Group Endpoint

---

storageClient/api.go
storageClient/storageClient.go

In the api.go file-> I added more types than I currently need. Only need DeleteGroupRequest for this endpoint
Also, testing will be added after endpoint is done

adding api types and path for endpoint

---

storageClient/api.go
storageClient/storageClient.go
storageClient/storageClient_test.go

i decided this needed to be done before the list shared records with group so ill leave those changes but wont push them until this is complete

sharing with groups

---

pdsClient/api.go
storageClient/api.go
storageClient/storageClient.go
storageClient/storageClient_test.go

The other branch got out of state very badly so i transferred the changed to this clean branch. When all fails, ABORT

listing all shared records to a group

---

crypto.go
pdsClient/api.go
pdsClient/pdsClient.go
storageClient/api.go
storageClient/storageClient_test.go

Attempt at creating this function

Decrypting group records

---

storageClient/api.go
storageClient/storageClient_test.go

add member count

---

identityClient/api.go
identityClient/identityClient.go
identityClient/identityClient_test.go
pdsClient/api.go
pdsClient/pdsClient.go

- Group Membership Application Mapper
- Realm Public Info
- Management of User Groups
- Group Attributes
- Default Groups
- Client Info (PDS)
- Tests for ^

Additional features for terraform resources

---

identityClient/api.go
identityClient/identityClient.go
identityClient/identityClient_test.go

The client side support for the new identity endpoint for fetching private realm info

client side support for realm private info endpoint

---

identityClient/api.go
identityClient/identityClient_test.go

Tests will be copied when identity gets approved

extending search identities to search by clientID

---

clientServiceClient/api.go
clientServiceClient/clientServiceClient.go

This is the client side support for patching signing keys

Client Side Signing Key Patch 

---

crypto.go
file/file.go
storageClient/storageClient_test.go

Uses tempFiles instead of hard-coded file names to avoid any conflicts with other files with these names

Update file names

---

identityClient/api.go
identityClient/identityClient.go
identityClient/identityClient_test.go

Client Side for Realm Settings Update + happy path tests

Realm Settings Update 

---

Makefile
clientServiceClient/clientServiceClient.go
identityClient/identityClient_internal_test.go
identityClient/identityClient_test.go

Adding a new path for register client

Updating Realm Names in test to use unique strings

---

Makefile
accountClient/accountClientV2.go
accountClient/accountClientV2_test.go
accountClient/accountClient_test.go
accountClient/api.go
test/test.go

Updates 
* Client side endpoint for Account Deletion Endpoint
* Removed unused tests 
* Created a make file target 
* Added happy path tests (CURRENTLY ONE RETURNS A 409 WILL UPDATE Comment once test passes)

[WR126] Client Side Endpoint

---

clientServiceClient/clientServiceClient.go

This is the endpoint we talked about in standup

[PLAT718] Add internal register endpoint

---

keycloakClient/api.go
keycloakClient/keycloakClient.go

This PR is a bit big, Reason:
* I began with roles CRUD
* Had conflicts with groups not able to use keycloak client v2 roles 
* looked into it and it was more effort than just doing groups! 
**I will continue to make the base branch the PR before since i need the functionality to keep working**

[PLAT718] Roles Groups and Group Mapping CRUD

---

keycloakClient/api.go
keycloakClient/keycloakClient.go

Would love some ideas on how to make ` GetClients` less sketchy 
* You can pass in as many query params, and its the only one right now that creates its own request and sends it to a new function to get the headers and be sent

[PLAT718] CRUD Client

---

keycloakClient/api.go
keycloakClient/keycloakClient.go

Update to create in order to not take an extra field, and added Delete Get and Put

[PLAT718]  Realm Update Read and Delete

---

keycloakClient/api.go
keycloakClient/keycloakClient.go

Added types that were still being pulled from keycloak client! and the forgotten function of auto refresh tokens
Officially fully switched over

[PLAT718] Const Types Transfer and auto refresh tokens

---

go.mod
go.sum
keycloakClient/api.go
keycloakClient/keycloakClient.go

Switching login to gentleman request

Update Initiate Login with Gentleman Request

---

accountClient/accountClientV2_test.go
identityClient/api.go
identityClient/identityClient.go

Happy Path tests (copy pasta) coming soon

[WR116] Internal Delete

---

clientServiceClient/api.go
clientServiceClient/clientServiceClient.go
storageClient/api.go
storageClient/storageClient.go

Clients for new endpoints for historical reconciler. Tests are currently in service code. Tests will need to be added here later.

Wash 1031 search health

---

identityClient/api.go
identityClient/identityClient.go
identityClient/identityClient_internal_test.go

- tests the cases where a username, userID or a clientID is provided

[WASH-1055] Tests for identity login audits

---

storageClient/storageClient_test.go

- happy path tests for checking that an account is unlocked before updating the password note

[WASH1041] Test account lock in password update

---

identityClient/identityClient.go

PLAT745] Encode the username for internal delete

---

storageClient/storageClient_test.go

Tests that updating notes is successful for notes with & without EACP

[WASH1049] More tests for account locking & notes

---

identityClient/api.go

API Spec and Identity Service PRS Coming

[WR225] Add requestor

---

keycloakClient/keycloakClient.go

- Add & remove realm roles from a user
- Remove realm roles from a user (add already exists)

[WR194] Add endpoints for adding, removing roles

---

identityClient/identityClient_test.go

Didnt push with my last branch... thought i had

[WR208] Update Tests to use non internal endpoints

---

identityClient/api.go
identityClient/identityClient.go

Will also add happy path tests here

[WR187] Endpoint for key check with federation

---

identityClient/api.go

Committing this so I can update identity service with a new version

[WR-253] Sync mfa settings api

---

crypto.go
identityClient/api.go
identityClient/identityClient.go
storageClient/storageClient.go

- Adds endpoint for notePrimeByName & returns password update info from initiate login

[WR187] Endpoint for key check with multi realm

---

identityClient/api.go

https://toznysecurity.atlassian.net/browse/WR-262
https://github.com/tozny/identity-management-service/pull/305

[WR-262] add AccessPolicies to AccessRequestGroupResponse

---

identityClient/api.go
identityClient/identityClient.go

note the base branch of `feature/mpc-jira-plugin`. this way we don't need to expect failures in our integration tests.

[WR-302] add CreatePAMJiraPlugin method

---

identityClient/api.go
identityClient/identityClient.go

[WR-302] add DeletePAMJiraPlugin method

---

identityClient/api.go
identityClient/identityClient.go

[WR-302] add UpdatePAMJiraPlugin method

---

pdsClient/pdsClient_test.go

Add test email

---

identityClient/identityClient_test.go

These tests were outdated with respect to the tests in Identity Service. No password note is written for new Identities, so `GetFederatedIdentitiesForSync` fails to read the note from storage service when performing the password note check.

Fix failing Federation tests

---

identityClient/api.go
identityClient/identityClient.go
keycloakClient/api.go
keycloakClient/client_applications.go
keycloakClient/keycloakClient.go

Pre warning: Will need to add context to some structs

Wr 295 group keycloak endpoints

---

identityClient/identityClient.go
identityClient/identityClient_test.go
keycloakClient/keycloakClient.go

need to write a test for this to make sure keycloak will unescape!

[WR-311] Bug Fix for Path Parameter

---

accountClient/accountClientV2_test.go

- Test email address updated to

Update email address

---

identityClient/api.go
identityClient/identityClient.go
keycloakClient/api.go
keycloakClient/keycloakClient.go

identity service calls to new endpoints for registering 
* initiate webauthn challenge api
* register mfa device api
note the base feature branch.

[WASH-1124] webauthn registration flow API

---

identityClient/api.go
identityClient/identityClient.go
keycloakClient/api.go

The base branch is the feature branch, and here are the client side resources

[WR388] Update Credential Representation

---

keycloakClient/keycloakClient.go

ha 😅 probably coulda asked katie to add this into her pr. my bad! missed a `?` to join the url to the query

[WASH-1124] fix WebAuthn registration POST query

---

identityClient/api.go
identityClient/identityClient.go

Ran all MFA tests in Identity and they passed ~

[WR-388] Update GET to POST for list mfa devices

---

identityClient/api.go
identityClient/identityClient.go
keycloakClient/keycloakClient.go

Drafted the PR (https://github.com/tozny/identity-management-service/pull/371/files) for the actual endpoint until I add more tests to it. The happy path works, though!

[WR-385] Remove MFA endpoint client methods

---

Makefile
pdsClient/pdsClient_test.go

adds make commands for testing only the external client funcs of account & pds services

improve dev UX of testing external endpoints

---

storageClient/storageClient_test.go

Plat 941 delete group members

---

Makefile
storageClient/api.go
storageClient/storageClient.go
storageClient/storageClient_internal_test.go

Client Side endpoint --> Matches the current API Spec

[PLAT-958] Add internal groups fetch endpoint

---

storageClient/api.go
storageClient/storageClient.go
storageClient/storageClient_internal_test.go

new endpoint for the indexer to pull the shared with groups field

[PLAT-940] New Internal Storage path for allowed reads

---

storageClient/api.go
storageClient/storageClient.go

in draft status with @lily-tsou

[PLAT-969] Client side endppoint for internal allowed reads

---

secureComputeClient/api.go
secureComputeClient/secureComputeClient.go
secureComputeClient/secureComputeClient_test.go

Added Secure Compute Basic Client 
* Added healthcheck and service check test! as well as the skeleton for the required files

[PLAT-964] Add secure compute client

---

Makefile
secureComputeClient/api.go
secureComputeClient/secureComputeClient.go

[PLAT-976] Client side endpoints

---

Makefile
secureComputeClient/api.go
secureComputeClient/secureComputeClient_test.go

[PLAT-976] Add test for new endpoints

---

identityClient/api.go
identityClient/identityClient_test.go

[WR-425] Custom Forgot Password Link test

---

identityClient/api.go
identityClient/identityClient.go
keycloakClient/api.go
keycloakClient/keycloakClient.go

While working on Keycloak Azure! I had an idea to make this work! and it worked

Wr 454 get realm identity count

---

identityClient/api.go

[WR-329] Update Federated Identities

---

identityClient/api.go
identityClient/identityClient_test.go

Fixing code that i pushed from a developer and merging it with the endpoint it should be in

Fix realm info

---

identityClient/api.go
identityClient/identityClient.go

Add attribute to register and update attribute handler client side

[PLAT-1348] Add update attribute handler

---

clientServiceClient/clientServiceClient.go
storageClient/storageClient.go

Add below API wrappers for deleting a user.
- Delete Client : Adds client to client cleanup table in client service.
- Delete Client Records : Deletes all client records and it's keys.
- Delete Client Groups : Deletes all client groups and it's keys.

Tozflow 326 delete records groups

---

storageClient/api.go
storageClient/storageClient.go

[TOZFLOW-416] Update pagination

---

storageClient/api.go
storageClient/storageClient.go

name change FetchGroupsByCapability => FetchGroupIDsByCapability

Plat 1611 fetch groupIDs by capability

---

storageClient/api.go
storageClient/storageClient.go

endpoint for FetchUserGroupCapabilities

Plat 1631 create storage service endpoint for fetching a single client s membership

---

identityClient/api.go
identityClient/identityClient.go
storageClient/api.go
storageClient/storageClient.go

- Added structs for fetching client realms
- Added InternalFetchClientsRealms method to E3dbIdentityClient

 [PLAT-1631] InternalFetchClientsRealms

---

storageClient/api.go
storageClient/storageClient.go

These API wrappers are added here for tests.

Group folder API's.

---

pdsClient/pdsClient.go

Created records shared endpoint in pdsClient

Added shared record service call

---

clientServiceClient/api.go
clientServiceClient/clientServiceClient.go
go.mod
go.sum
storageClient/api.go
test/test.go

Wr 607 upgrade o auth library
